#!/bin/bash
python -m sim -f data/bitmex_1day.csv -x span=100 -x greediness=1.0 -x qty_to_trade=3 -x loss_limit=3 -l test/quick_sim_test

result=`diff -r test/quick_sim_test test/ref`

if [ -z $result ]
then
	echo " --------------------------- "
	echo " --------------------------- "
	echo " PASSED!                     "
	echo " --------------------------- "
	echo " --------------------------- "
else
	echo " --------------------------- "
	echo " --------------------------- "
	echo " FAILED: quant diff detected "
	echo " --------------------------- "
	echo " --------------------------- "
	echo " showing diff: "
	echo $result
fi



