#!/bin/bash

python -m sim --files data/20180701-1h-%TYPE%.csv.gz --log-dir test/test1 -b '2018-07-01 00:00:00' -e '2018-07-01 00:10:00' --tactics SimTLT -x /SimTLT/qty_to_trade=5 > /tmp/a
result=`diff -r test/test1 test/ref1`
if [ -z $result ]
then
	echo " --------------------------- "
	echo " --------------------------- "
	echo " PASSED!                     "
	echo " --------------------------- "
	echo " --------------------------- "
else
	echo " --------------------------- "
	echo " --------------------------- "
	echo " FAILED: quant diff detected "
	echo " --------------------------- "
	echo " --------------------------- "
	echo " showing diff: "
	echo $result
fi

python -m sim --files data/20180701-1h-%TYPE%.csv.gz --log-dir test/test2 -b '2018-07-01 00:00:00' -e '2018-07-01 00:10:00' --tactics SimTMT -x /SimTMT/qty_to_trade=5 > /tmp/b
result=`diff -r test/test2 test/ref2`
if [ -z $result ]
then
	echo " --------------------------- "
	echo " --------------------------- "
	echo " PASSED!                     "
	echo " --------------------------- "
	echo " --------------------------- "
else
	echo " --------------------------- "
	echo " --------------------------- "
	echo " FAILED: quant diff detected "
	echo " --------------------------- "
	echo " --------------------------- "
	echo " showing diff: "
	echo $result
fi


